site_name: "Портфолио Жуковой Таисии"
site_author: "Жукова Таисия Ильинична"
site_description: "Портфолио работ по программированию и информационным системам"

theme:
  name: material
  language: ru

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

  palette:
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Светлая тема

    - scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Тёмная тема

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Главная: index.md
  - Обо мне: about.md
  - Программирование:
      - 3 семестр:
          - Two Sum: projects/two_sum.md
          - Вычисление деления: projects/division_calculation.md
          - Бинарное дерево. Рекурсия: projects/binary_tree_recursion.md
          - Телеграм-бот для библиотеки: projects/telegram_bot_libraries.md
      - 4 семестр:
          - Итераторы, генераторы, сопрограммы: projects/iterators_generators_coroutines.md
          - Паттерн "Observer": projects/observer_pattern_report.md
          - Паттерны проектирования: projects/design_patterns_lab.md
          - Шаблон "Одиночка": projects/singleton_pattern.md
          - Основные концепции ООП: projects/oop_concepts_python.md
  - Информационные системы и БД:
      - 1 семестр:
          - Задание 1. Создание простой БД: isbd/sem1_task1.md
          - Задание 2. Сохранение целостности: isbd/sem1_task2.md
          - Задание 3. Реляционная алгебра: isbd/sem1_task3.md
          - Задание 4. Реляционная алгебра: isbd/sem1_task4.md
          - Задание 5. Проектирование БД (НФБК): isbd/sem1_task5.md
          - Задание 6. Нормализация БД: isbd/sem1_task6.md
      - 2 семестр:
          - Лабораторная работа №6 (SQLite): isbd/sqlite_lab.md
          - Сертификаты Stepik: isbd/stepik_cert.md
          - Финальное задание:
              - Часть 1. Создание ЛР: isbd/final_project_part1.md
              - Часть 2. Решение ЛР: isbd/final_project_part2.md
